category/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "category"
urlpatterns = [
    path("categoryadd/", views.add_category, name="categoryadd"),
    path("categoryread/", views.show_category, name="categoryread"),
    path(
        "deletecategory/<int:id>", views.delete_category, name="deletecategory"
    ),
    path("<int:id>", views.update_category, name="updatecategory"),
]

login/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "login"
urlpatterns = [
    path("", views.login_user, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout_user, name="logout"),
    path(
        "activate-user/<uidb64>/<token>", views.activate_user, name="activate"
    ),
    path(
        "password_reset", views.password_reset_request, name="password_reset"
    ),
    path("dashboard", views.show_dashboard, name="dashboard"),
]

product/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "product"
urlpatterns = [
    path("productadd/", views.create_product, name="productadd"),
    path("productread/", views.show_product, name="productread"),
    path("deleteuser/<int:id>/", views.delete_product, name="deleteproduct"),
    path("<int:id>/", views.update_product, name="updateproduct"),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path("adduser/", views.create_user, name="useradd"),
    path("userread/", views.viewUser, name="userread"),
    path("deleteuser/<int:id>/", views.delete_user, name="deletedata"),
    path("<int:id>/", views.update_user, name="updateuser"),
]

userCRUD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("product/", include("product.urls")),
    path("category/", include("category.urls")),
    path("", include("login.urls")),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

login/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserManager(BaseUserManager):
    def create_user(
        self,
        email,
        full_name=None,
        password=None,
        is_active=True,
        is_staff=False,
        is_admin=False,
    ):
        if not email:
            raise ValueError("Users must have an email address")
        if not password:
            raise ValueError("Users must have a password")
        user_obj = self.model(
            email=self.normalize_email(email), full_name=full_name
        )
        user_obj.set_password(password)  # change user password
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.active = is_active
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, email, full_name=None, password=None):
        user = self.create_user(
            email, full_name=full_name, password=password, is_staff=True
        )
        return user

    def create_superuser(self, email, full_name=None, password=None):
        user = self.create_user(
            email,
            full_name=full_name,
            password=password,
            is_staff=True,
            is_admin=True,
        )
        return user


class User(AbstractBaseUser):
    is_email_verified = models.BooleanField(default=False)
    email = models.EmailField(max_length=255, unique=True)
    full_name = models.CharField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=True)  # can login
    staff = models.BooleanField(default=False)  # staff user non superuser
    admin = models.BooleanField(default=False)  # superuser
    timestamp = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = "email"  # username

    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        if self.full_name:
            return self.full_name
        return self.email

    def get_short_name(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(
        null=True,
        blank=True,
        upload_to="images/",
        default="images/default.png",
    )

    def __str__(self):
        return self.user.email

login/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from login.models import UserProfile


User = get_user_model()


class UserAdminCreationForm(forms.ModelForm):

    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password confirmation", widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = (
            "full_name",
            "email",
        )

    def clean_password2(self):

        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):

        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ("full_name", "email", "password", "active", "admin")

    def clean_password(self):
        return self.initial["password"]


class LoginForm(forms.Form):
    email = forms.EmailField(label="Email")
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterForm(forms.ModelForm):

    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password confirmation", widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = (
            "full_name",
            "email",
        )

    def clean_password2(self):

        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):

        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["image"]

        widgets = {
            "image": forms.FileInput(
                attrs={
                    "class": "form-control-file",
                }
            ),
        }

login/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.db.models.query_utils import Q
from django.http import HttpResponse
from django.contrib.messages import constants
from django.urls import reverse
from django.http.response import HttpResponseRedirect
from django.views.generic import FormView
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from login.models import UserProfile
from django.utils.encoding import (
    force_bytes,
    force_str,
    force_text,
    DjangoUnicodeDecodeError,
)
from .utils import generate_token
from django.conf import settings
from django.core.mail import EmailMessage

from django.shortcuts import redirect, render


from .forms import LoginForm, RegisterForm, User, UserImageForm

# Create your views here.


def send_activation_email(user, request):

    current_site = get_current_site(request)
    email_subject = "Activate Your Account"
    email_body = render_to_string(
        "activation.html",
        {
            "user": user,
            "domain": current_site,
            "uid": urlsafe_base64_encode(force_bytes(user.id)),
            "token": generate_token.make_token(user),
        },
    )

    email = EmailMessage(
        subject=email_subject,
        body=email_body,
        from_email=settings.EMAIL_FROM_USER,
        to=[user.email],
    )
    email.send()


def login_user(request):
    if request.user.is_authenticated:
        print("authenticated")
        return HttpResponseRedirect("user/userread")

    if request.method == "POST":
        fm = LoginForm(request.POST)
        if fm.is_valid():
            email = fm.cleaned_data.get("email")
            password = fm.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)

            """ if not user.is_email_verified:
                messages.error(request, "Email is not verifed")
                return HttpResponseRedirect("/") """
            if user is not None:
                login(request, user)
                messages.success(
                    request,
                    "Login successful",
                )
                return HttpResponseRedirect("user/userread")
    fm = LoginForm()
    return render(request, "login.html", {"form": fm})


def register(request):

    if request.method == "POST":
        form = RegisterForm(request.POST or None)
        if form.is_valid():

            user = form.save()

            user.active = False
            user.save()
            send_activation_email(user, request)

            messages.success(
                request,
                "A link has been sent to your email. Please click on the link"
                " to verify",
            )
            return HttpResponseRedirect("/register")
        else:
            messages.error(request, "Cannot register. Please try again")
            return redirect("/register")
    else:
        form = RegisterForm()
    return render(request, "register.html", {"form": form})


def logout_user(request):
    logout(request)

    return HttpResponseRedirect("/")


def activate_user(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)

    except Exception as e:
        user = None

    if user and generate_token.check_token(user, token):
        # user.is_email_verified = True
        user.active = True
        user.save()
        messages.success(request, "Email Verified. Please sign in to continue")
        return HttpResponseRedirect("/")
    return render(request, "activation-failed.html", {"user": user})


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data["email"]
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "password_reset_email.html"
                    c = {
                        "email": user.email,
                        "domain": "127.0.0.1:8000",
                        "site_name": "Website",
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        "token": default_token_generator.make_token(user),
                        "protocol": "http",
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(
                            subject,
                            email,
                            "admin@example.com",
                            [user.email],
                            fail_silently=False,
                        )
                    except BadHeaderError:
                        return HttpResponse("Invalid header found.")
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(
        request=request,
        template_name="password_reset.html",
        context={"password_reset_form": password_reset_form},
    )


def show_dashboard(request):
    try:
        profile = request.user.userprofile

    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)
        print(profile)

    if request.method == "POST":
        form = UserImageForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            data = form.save(commit=False)
            data.user = request.user
            data.save()

            return HttpResponseRedirect("dashboard")
        else:
            messages.error(request, "Could not upload image, try again.")
    else:
        form = UserImageForm(instance=profile)

        return render(request, "dashboard.html", {"form": form})

templates/activation-failed.html
<p>Somethin went wrong please try again</p>

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>User Add/Read</title>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback" />
  <!-- Font Awesome -->
  {% block csspart %}
  <link rel="stylesheet" href="{%static 'plugins/fontawesome-free/css/all.min.css' %}" />
  <!-- Theme style -->
  <link rel="stylesheet" href="{%static 'dist/css/adminlte.min.css' %}" />
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{%static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}" />
  {% endblock csspart %}
</head>

{% block bodytag %}
{% endblock bodytag%}

{% block nav%}
<div class="wrapper">
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        LogOut
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="{% url 'login:logout' %}">LogOut</a>
        <a class="dropdown-item" href="/password_reset">Password Reset</a>

      </div>
    </div>
  </nav>
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'login:dashboard'  %}" class="brand-link">
      <img src="{{ user.userprofile.image.url }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
        style="opacity: 0.8" />
      <span class="brand-text font-weight-light">{{user.full_name}}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->


      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search" />
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-users"></i>
              <p>
                USER
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'user:useradd' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add User</p>
                </a>
              </li>
            </ul>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'user:userread' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View User</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-arrow-alt-circle-right"></i>
              <p>
                Product
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'product:productadd' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add Product</p>
                </a>
              </li>
            </ul>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'product:productread' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View Product</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-edit"></i>
              <p>
                Category
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'category:categoryadd' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add Category</p>
                </a>
              </li>
            </ul>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'category:categoryread' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View Category</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
  {% endblock nav%}

  {% block bodycontent%}
  {% endblock bodycontent%}

  {% block redirect%}
  {% endblock redirect%}
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2021
      <a href="https://adminlte.io">Navneet Singh Rajbanshi</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

{% block addjquery %}
<!-- jQuery -->
<script src="{%static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{%static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge("uibutton", $.ui.button);
</script>
<!-- Bootstrap 4 -->
<script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{%static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{%static 'dist/js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{%static 'dist/js/demo.js' %}"></script>
<script src="https://kit.fontawesome.com/b45233a9f7.js" crossorigin="anonymous"></script>
{% endblock addjquery %}
</body>

</html>

templates/categoryread.html
{%extends "base.html" %} {% load static %} 
    <!-- Font Awesome -->

    {% block csspart %}
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  </head>
  {% endblock csspart %}

  {%block bodycontent%}
  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1>Category Table</h1>
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">General Form</li>
                </ol>
              </div>
            </div>
          </div>
          <!-- /.container-fluid -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <a class="btn btn-success" href="{% url 'category:categoryadd' %}" role="button">Add New Category</a>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Category name</th>
                    <th>Vendor</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                 
                  {% for data in datas %}
                  <tr>
                    <td>{{data.id}}</td>
                    <td>{{data.name}}</td>
                    <td>{{data.vendor}}</td>
                    <td>
                      <a class="btn btn-success" href="{% url 'category:updatecategory' data.id %}"
                        role="button">Edit</a>
                      <form action="{% url 'category:deletecategory' data.id %}" method="POST" class=d-inline>
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger" value="Delete">
                      </form>



                    </td>
                  </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
        <!-- /.content -->
    </div>
      <!-- /.content-wrapper -->
    {%endblock bodycontent%}

    {%block addjquery%}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- Page specific script -->
            <script
      src="https://kit.fontawesome.com/b45233a9f7.js"
      crossorigin="anonymous"
    ></script>
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
    {% endblock addjquery %}
  </body>
</html>

templates/get-session.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Get session</title>
</head>

<body>
    <h4>Get Session</h4>

</body>

</html>

templates/password_reset.html
{% load crispy_forms_tags %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container p-5">
        <h2 class="font-weight-bold mt-3">Reset Password</h2>
        <hr>
        <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
        </p>
        <form method="POST">
            {% csrf_token %}
            {{ password_reset_form|crispy }}
            <button class="btn btn-primary" type="submit">Send email</button>
        </form>
    </div>
</body>

</html>

templates/password_reset_done.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    {% block csspart %}
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    {% endblock csspart %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Password reset successful</title>
    <style>
      img {
        display: block;
        max-width: 100%;
        height: auto;
      }
    </style>
  </head>
  {%block bodycontent%}
  <body>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd">
      <a class="navbar-brand" href=""> Home </a>
    </nav>
    <div class="container mt-4 mb-4">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div
            class="card bg-white text-secondary align-items-center text-center"
          >
            
            <div class="card-body">
              <h5 class="card-title .bg-primary">Password reset complete</h5>
              <p class="card-text">
                This is a confirmation that your password has been successfully
                changed. Your won't be able to login with your old password now.
                Please log in with your new password.
              </p>

              <p class="card-text mt-3">Get back to the login page.</p>
              <a href="{% url 'login:login' %}" class="btn btn-danger"
                >Login</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
    <nav
      class="navbar navbar-light justify-content-center"
      style="background-color: #e3f2fd"
    >
      <li class="nav-item">
        Copyright &copy; 2021
        <a href="https://adminlte.io">Navneet Singh Rajbanshi</a>
        All rights reserved.
      </li>
    </nav>
    {%endblock bodycontent%} {%block addjquery%}
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    {% endblock addjquery %}
  </body>
</html>